export const FETCH_APPOINTMENTS_DATA = "FETCH_APPOINTMENTS_DATA"
export const FETCH_SETTINGS_DATA = "FETCH_SETTINGS_DATA"
export const FETCH_CLIENTS_DATA = "FETCH_CLIENTS_DATA"
export const FETCH_OPTIONS_DATA = "FETCH_OPTIONS_DATA"
